# Site settings
title: A Thought about Life:  Tech, Tunes, Attempts and Turbulations
header-img: img/home-bg.jpg
email: alexanderjburton@gmail.com
description: "Tech Blog by Alexander Burton."
baseurl: ""
url: "PurpIeHaze.github.io"
twitter_username: PvrpIeHaze
github_username:  PurpIeHaze
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
